title: Patoarchitekci
description: >
  Uwaga, rzucamy mięsem! czyli lekki podcast o chyba poważnym temacie jakim jest nowoczesna architektura w IT
permalink: ':title/'

logo: /assets/images/logo.jpg
timezone: Europe/Warsaw
url: "https://patoarchitekci.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: patoarchitekci
# Author Settings
author: Patoarchitekci # add your name
author-img: logo.jpg # add your photo
about-author: >
  lekki podcast o niby poważnym temacie jakim jest nowoczesna architektura w IT. <br>
  Słuchasz Patoarchitektów dzięki <b>Protopii</b>. Sprawdź, jak Patoarchitekci i Protopia mogą Ci pomóc ➡️ <a href="https://protopia.tech/">protopia.tech</a>
social-facebook: https://facebook.com/patoarchitekci/
social-github: patoarchitekci # add your Github handle
#social-linkedin: # add your Linkedin handle
social-email: kontakt@patoarchitekci.io
social-twitter: patoarchitekci
# Disqus
discus-identifier: patoarchitekci-io # add your discus identifier

# Tracker
analytics: UA-142509712-1

menu:
- title: Patoarchitekci
  url: /
- title: Gdzie słuchać?
  url: /gdzie-sluchac/
- title: O podcaście
  url: /o-podcascie/
- title: Szkolenia
  url: /szkolenia/
- title: Kontakt
  url: mailto:kontakt@patoarchitekci.io
- title: Regulamin
  url: https://app.easy.tools/terms/otwarte-pato
- title: Polityka prywatności
  url: https://app.easy.tools/policies/otwarte-pato

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 5
paginate_path: "/page/:num"

collections:
  news:
    output: false

defaults:
  - scope:
      path: ""
    values:
      cta: true

exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - yarn.lock
  - Gemfile
  - Gemfile.lock
  - CNAME
  - Docker.ps1
  - docker.sh
  - LICENSE
