title: Patoarchitekci
description: >
  Uwaga, rzucamy mięsem! czyli lekki podcast o chyba poważnym temacie jaki jest nowoczesna architektura w IT
permalink: ':title/'

logo: /assets/images/logo.png


url: "https://patoarchitekci.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: patoarchitekci
# Author Settings
author: Patoarchitekci # add your name
author-img: logo.png # add your photo
about-author: <b>Uwaga, rzucamy mięsem</b>, czyli lekki podcast o niby poważnym temacie jaki jest nowoczesna architektura w IT.
#social-twitter: # add your Twitter handle
#social-facebook: # add your Facebook handle
#social-github: artemsheludko # add your Github handle
#social-linkedin: # add your Linkedin handle
social-email: kontakt@patoarchitekci.io
social-twitter: patoarchitekci
# Disqus
discus-identifier: patoarchitekci-io # add your discus identifier

# Tracker
analytics: UA-142509712-1

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - yarn.lock
  - Gemfile
  - Gemfile.lock
  - CNAME
  - Docker.ps1
  - LICENSE