baseURL = "https://patoarchitekci.io/"
languageCode = "pl-PL"
title = "Patoarchitekci"

[params]
  description = "Stworzyliśmy ten podcast, bo sami szukaliśmy miejsca, które łączy wiedzę, praktykę i dystans do branży IT."
  
  # Social media
  [params.social]
    tiktok = "https://www.tiktok.com/@patoarchitekci_"
    discord = "https://discord.com/invite/78zPcEaP22"
    linkedin = "https://www.linkedin.com/company/patoarchitekci/"
    facebook = "https://www.facebook.com/patoarchitekci/"
    twitter = "https://x.com/patoarchitekci"
    instagram = "https://www.instagram.com/patoarchitekci"

  # Host profiles
  [params.hosts]
    [params.hosts.lukasz]
      linkedin = "https://www.linkedin.com/in/lukaszkaluzny/"
      twitter = "https://x.com/kaluzaaa"
    [params.hosts.szymon]
      linkedin = "https://www.linkedin.com/in/szymonwarda/"
      twitter = "https://x.com/maklipsa"
    
  # Podcast platforms
  [params.podcast]
    youtube = "https://www.youtube.com/@Patoarchitekci"
    spotify = "https://open.spotify.com/show/13wiwR1mmHD3PTBcMt9J9J"
    apple = "https://podcasts.apple.com/il/podcast/patoarchitekci/id1477067604"
    
  # Legal
  [params.legal]
    privacyPolicy = "https://app.easy.tools/policies/otwarte-pato"
    terms = "https://app.easy.tools/terms/otwarte-pato"
    
  # Training banner
  [params.trainingBanner]
    enabled = false
    text = "Do najbliższego szkolenia"
    highlight = "zostały 3 dni! 👉 Zapisz się teraz!"

  # Consultation
  [params.consultation]
    url = "https://outlook.office365.com/book/Spotkania@protopia.tech/s/rWrePx6FFEWNFvm6Dnv48w2"
    title = "Bezpłatna Konsultacja"
    purchaseUrl = "https://cart.easy.tools/checkout/patoarchitekci/szybkie-konsultacje"
    advisoryUrl = "https://protopia.tech/doradztwo"
    
  # Footer
  [params.footer]
    copyright = "© Protopia 2025"
    
  # Szkolenia - globalne dane
  [params.trainings]
    [params.trainings.coordinator]
      name = "Mikołaj Szczerbicki"
      phone = "+48 667 013 893"
      email = "mikołaj.szczerbicki@protopia.tech"
    [params.trainings.certificate]
      included = true
      description = "Oficjalne potwierdzenie zdobytych skilli"

[menu]
  [[menu.main]]
    name = "Gdzie słuchać"
    url = "/#platforms"
    weight = 1
  [[menu.main]]
    name = "O nas"
    url = "/#hosts"
    weight = 2
  [[menu.main]]
    name = "Szkolenia"
    url = "/szkolenia/"
    weight = 3
  [[menu.main]]
    name = "Bezpłatna Konsultacja"
    url = "https://outlook.office365.com/book/Spotkania@protopia.tech/s/rWrePx6FFEWNFvm6Dnv48w2"
    weight = 4
    [menu.main.params]
      target = "_blank"
  [[menu.main]]
    name = "Kontakt"
    url = "/kontakt/"
    weight = 5

[permalinks]
  episodes = "/:contentbasename/"
  trainings = "/szkolenia/:contentbasename/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "newsletter-rss", "social-rss"]

[outputFormats]
  [outputFormats.newsletter-rss]
    name = "RSS"
    mediaType = "application/rss+xml"
    baseName = "newsletter"
    path = ""
    
  [outputFormats.social-rss]
    name = "RSS"
    mediaType = "application/rss+xml"
    baseName = "social"
    path = ""
    
  [outputFormats.debug-rss]
    name = "RSS"
    mediaType = "application/rss+xml"
    baseName = "debug"
    path = ""