#!/usr/bin/env python3
"""Refresh baked-in ticket stock for the conference and trainings.

Fetches the real remaining quantity from each easy.tools checkout page and bakes
it into the static build so crawlers / no-JS visitors / schema.org see the truth
instead of the hardcoded fallback (99 / participants.max). The live JS counter in
the page keeps refreshing on top of this at request time.

Outputs:
  - data/tickets.yaml          : map of {easytools-slug: remaining}, read by Hugo
                                 as .Site.Data.tickets (training fallback number).
  - static/konferencja/index.html : <span data-tickets-left>N</span> patched in place.

On a failed fetch the previous value is kept (never wiped), so a flaky easy.tools
response does not regress the baked numbers. The daily GitHub Action commits only
when a number actually changed, which in turn triggers the Cloudflare Pages build.
"""

import datetime
import glob
import os
import re
import sys

import requests
import yaml

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHECKOUT_BASE = "https://cart.easy.tools/checkout/patoarchitekci"
TRAININGS_DIR = os.path.join(REPO_ROOT, "data", "trainings")
TICKETS_FILE = os.path.join(REPO_ROOT, "data", "tickets.yaml")
CONFERENCE_HTML = os.path.join(REPO_ROOT, "static", "konferencja", "index.html")
CONFERENCE_SLUG = "konferencja-pato-200"

# Mirrors the parser in functions/api/tickets-left.js
QUANTITY_RE = re.compile(r'"has_quantity":true,"quantity":(\d+)')
SLUG_RE = re.compile(r"^[a-z0-9-]+$")
SPAN_RE = re.compile(r"(<span data-tickets-left>)\d+(</span>)")

TIMEOUT = 20
HEADERS = {"user-agent": "patoarchitekci-site/1.0 (ticket-sync)"}


def discover_slugs():
    """Conference + trainings that are actually on sale.

    A training is "on sale" when it mirrors the template's $showLiveTickets
    (the page that renders the live counter):
      active (not false) + has purchase_url + not waitlist_only + future date.
    Waitlist-only / past / inactive trainings show no counter, so baking a
    number for them would be dead weight.
    """
    today = datetime.date.today().isoformat()
    slugs = [CONFERENCE_SLUG]
    for path in sorted(glob.glob(os.path.join(TRAININGS_DIR, "*.yaml"))):
        with open(path, encoding="utf-8") as fh:
            data = yaml.safe_load(fh) or {}
        url = data.get("purchase_url") or ""
        slug = url.rstrip("/").rsplit("/", 1)[-1] if url else ""
        if not (slug and SLUG_RE.match(slug)):
            continue
        if data.get("active") is False or data.get("waitlist_only"):
            continue
        dates = data.get("dates") or []
        if not dates or str(dates[0]) <= today:  # no date or already past
            continue
        if slug not in slugs:
            slugs.append(slug)
    return slugs


def fetch_remaining(slug):
    """Return the live remaining quantity, or None if it can't be determined."""
    try:
        res = requests.get(f"{CHECKOUT_BASE}/{slug}", headers=HEADERS, timeout=TIMEOUT)
    except requests.RequestException as err:
        print(f"  ! fetch failed for {slug}: {err}", file=sys.stderr)
        return None
    if res.status_code != 200:
        print(f"  ! non-OK ({res.status_code}) for {slug}", file=sys.stderr)
        return None
    match = QUANTITY_RE.search(res.text)
    if not match:
        print(f"  ! quantity pattern not found for {slug}", file=sys.stderr)
        return None
    return int(match.group(1))


def load_existing():
    if not os.path.exists(TICKETS_FILE):
        return {}
    with open(TICKETS_FILE, encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


def write_tickets(tickets):
    header = (
        "# Auto-generated by scripts/update_tickets.py (GHA: update_tickets.yml).\n"
        "# Real remaining ticket stock per easy.tools slug. Do not edit by hand.\n"
    )
    body = "".join(f"{slug}: {tickets[slug]}\n" for slug in sorted(tickets))
    with open(TICKETS_FILE, "w", encoding="utf-8") as fh:
        fh.write(header + body)


def patch_conference_html(remaining):
    if remaining is None or not os.path.exists(CONFERENCE_HTML):
        return
    with open(CONFERENCE_HTML, encoding="utf-8") as fh:
        html = fh.read()
    patched, n = SPAN_RE.subn(rf"\g<1>{remaining}\g<2>", html)
    if n and patched != html:
        with open(CONFERENCE_HTML, "w", encoding="utf-8") as fh:
            fh.write(patched)
        print(f"  -> patched {n} conference span(s) to {remaining}")


def main():
    previous = load_existing()
    tickets = {}  # rebuilt from the currently-on-sale set, so stale slugs drop out
    print("Refreshing ticket stock from easy.tools...")
    for slug in discover_slugs():
        remaining = fetch_remaining(slug)
        if remaining is None:
            # No quantity cap on the checkout (unlimited seats) or a transient
            # fetch error. Keep the last known value if we had one, else skip so
            # the page falls back to participants.max.
            kept = previous.get(slug)
            if kept is not None:
                tickets[slug] = kept
            print(f"  {slug}: no quantity / fetch failed -> keep previous ({kept})")
            continue
        prev = previous.get(slug)
        tickets[slug] = remaining
        state = "SOLD OUT" if remaining == 0 else str(remaining)
        flag = "" if prev == remaining else f"  (was {prev})"
        print(f"  {slug}: {state}{flag}")
        if slug == CONFERENCE_SLUG:
            patch_conference_html(remaining)
    write_tickets(tickets)
    print(f"Wrote {TICKETS_FILE}")


if __name__ == "__main__":
    main()
