name: Publish Podcast Episode

on:
  workflow_dispatch:
    inputs:
      episode_number:
        description: 'Episode Number to Publish'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Specify desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Publish Script
        id: publish_script
        run: |
          python scripts/publish_episode.py --episode-number ${{ github.event.inputs.episode_number }}
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          EPISODES_TABLE_NAME: ${{ secrets.EPISODES_TABLE_NAME || 'episodes' }} # Allow override via secret, default to 'episodes'
          LINKS_TABLE_NAME: ${{ secrets.LINKS_TABLE_NAME || 'links' }}      # Allow override via secret, default to 'links'
          TAGS_TABLE_NAME: ${{ secrets.TAGS_TABLE_NAME || 'tags' }}        # Allow override via secret, default to 'tags'
          IS_PUBLISHED_FIELD: ${{ secrets.IS_PUBLISHED_FIELD || 'is_published' }} # Allow override via secret, default to 'is_published'
          # Add other necessary secrets as environment variables

      - name: Commit and Push changes
        uses: EndBug/add-and-commit@v9
        with:
          # Add the directories containing the generated files
          add: '_posts/ assets/img/'
          message: 'Publish episode ${{ github.event.inputs.episode_number }}'
          default_author: github_actions # Use the default GitHub Actions bot user
          # Ensure pushing to the correct branch (default is usually the branch the workflow runs on)
          # push: 'true' # Default is true, explicitly setting for clarity if needed

      # - name: Trigger GitHub Pages build
      #   # This step is typically unnecessary if GitHub Pages is configured
      #   # to build from the branch being pushed to.
      #   # The push from the 'add-and-commit' step should trigger it automatically.
      #   # If needed, you might trigger a separate workflow using:
      #   repository_dispatch:
      #     types: [build-pages] # Or use a specific action if available

      # Optional steps (e.g., if Airtable update is moved here, or webhook calls are needed)
      # - name: Update Airtable Status (Alternative)
      #   if: success()
      #   run: echo "Call script/API to update Airtable status if moved from Python script"
      
      # - name: Call Other Webhooks
      #   if: success()
      #   run: |
      #     curl -X POST YOUR_WEBHOOK_URL_1?record_id=RECORD_ID&spreaker_id=SPREAKER_ID
      #     curl -X POST YOUR_WEBHOOK_URL_2?record_id=RECORD_ID&spreaker_id=SPREAKER_ID 